import {
  background,
  border,
  extendTheme,
  flexbox,
  useListStyles,
} from "@chakra-ui/react";

import "@fontsource/rubik/300.css";
import "@fontsource/rubik/400.css";
import "@fontsource/rubik/500.css";
import "@fontsource/rubik/600.css";
import "@fontsource/rubik/700.css";
import "@fontsource/nanum-myeongjo/400.css";
import "@fontsource/nanum-myeongjo/700.css";
import "@fontsource/nanum-myeongjo/800.css";
import "@fontsource/dancing-script/400.css";
import "@fontsource/dancing-script/600.css";
import "@fontsource/dancing-script/700.css";

// Lato Font Source
import "@fontsource/lato/300.css";
import "@fontsource/lato/400.css";
import "@fontsource/lato/700.css";
// import '@fontsource/berkshire-swash/400.css';

const breakpoints = {
  sm: "320px",
  md: "768px",
  lg: "992px",
  xl: "1280px",
  "2xl": "1600px",
};
const activeLabelStyles = {
  transform: "scale(0.85) translateY(-20px)",
  color: "primary.color1",
  fontSize: "xs",
  fontWeight: "semibold",
};
const outerContainer = {
  maxW: [
    "full",
    "container.sm",
    "container.md",
    "container.lg",
    "container.xl",
    "container.2xl",
  ],
  px: ["16px", "16px", "16px", "16px", "16px", "16px"],
};
export const theme = extendTheme({
  breakpoints,
  config: {
    cssVarPrefix: "sh",
  },
  styles: {
    global: {
      body: {
        bg: "white",
        color: "primary.black",
      },
      a: {
        // color: 'teal.500',
        _hover: {
          textDecoration: "none",
        },
      },
    },
  },
  zIndices: {
    one: 1,
    two: 2,
    three: 3,
    four: 4,
    five: 5,
    absoluteFlex: 10,
    headerFix: 11,
  },
  shadows: {
    light: "0px 0px 8px rgba(0, 0, 0, 0.1)",
    headerShadow: "0px 4px 6px rgba(0, 0, 0, 0.1)",
  },
  fontFamily: {
    playfair: "Playfair Display",
    inter: "Inter",
    berkshire: "Berkshire Swash",
    rubik: "rubik",
    nanum: "nanum myeongjo",
    dancingS: "Dancing Script",
    lato: "Lato",
  },
  fonts: {
    heading: "Playfair Display",
    body: "rubik",
  },
  fontSizes: {
    h1: "19rem",
    fs11: "0.68rem",
    fs13: "0.813rem",
    fs40: "2.5rem",
    fs69: "4.3rem",
    fs125: "7.18rem",
  },
  space: {
    formTop: "5.5rem",
    13: "3.25rem",
    15: "3.75rem",
    17: "4.25rem",
    18: "4.5rem",
    26: "6.5rem",
    30: "7.5rem",
    space10: "0.625rem",
    space30: "1.87rem",
    space42: "2.68rem",
    space44: "2.75rem",
    space49: "3.06rem",
    space60: "3.75rem",
    space52: "3.35rem",
    space72: "4.5rem",
    size75: "4.68rem",
    space78: "4.875rem",
    space61: "3.81rem",
    space26: "1.625rem",
    space92: "5.75rem",
    space106: "6.625rem",
    space116: "7.25rem",
    space120: "7.5rem",
    space136: "8.5rem",
    space160: "10rem",
    navMobileSpace: "0.875rem",
  },
  sizes: {
    h1: "19rem",
    h2: "2.625rem",
    fs13: "0.813rem",
    fs20: "1.25rem",
    size18: "1.125rem",
    size32: "2rem",
    size40: "5rem",
    size60: "3.75rem",
    size84: "5.25rem",
    size120: "7.5rem",
    size130: "8.125rem",
    size160: "10rem",
    size200: "12.5rem",
    size180: "11.25rem",
    size183: "11.5rem",
    "3.1xs": "13.1rem",
    size235: "14.68rem",
    size255: "15.9rem",
    size270: "16.87rem",
    size280: "17.5rem",
    size288: "18rem",
    size298: "18.5rem",
    size303: "18.9rem",
    size311: "19.4rem",
    size400: "25rem",
    size470: "29.37rem",
    size328: "20.5rem",
    size330: "20.625rem",
    size352: "22rem",
    size355: "22.188rem",
    size366: "22.875rem",
    size436: "27.25rem",
    size534: "33.34rem",
    size544: "34rem",
    size568: "35.5rem",
    size592: "37rem",
    size598: "37.375rem",
    size640: "40rem",
    scrollHeight: "10.625rem",
    w736: "46rem",
    size864: "54rem",
    size928: "58rem",
    formWrapper: "22rem",
    otpWrapper: "22.5rem",
    OtpFrom: "3.75rem",
    smp: "26.25rem",
    sliderWrap: "58.375rem",
    contentWrap: "70rem",
    container: {
      sm: "540px",
      md: "720px",
      lg: "992px",
      xl: "1152px",
      "2xl": "1536px",
    },
  },
  colors: {
    primary: {
      color1: "#372045",
      color2: "#4b2b5d",
      color3: "#63377c",
      color4: "#b19bbd",
      color5: "#825f96",
      color6: "#403D58",
      black: "#0C0312",
      lightBlack: "#6d6871",
      lightBlack1: "#333143",
      white: "#ffffff",
    },
    secondary: {
      lightText: "#a594a6",
      lightText1: "#f4ede4",
      lightBg: "#f3ecd7",
      success: "#6a8b53",
      color1: "#faf7ef",
    },
    error: "#c4211a",
    tableHeaderBg: "#F4EDE4",
    borderColor: {
      color1: "#cecdd0",
      color2: "#9e8b9f",
      color3: "#9e9aa0",
    },
    background: {
      bgHeader: "#f4ede4",
      bgSubNavActive: "#9e8b9f",
      bgTransparent: "transparent",
      gray1: "#f9f8fa",
      gray2: "#F6F6F6",
      gray3: "#E5E5E5",
      gray4: "#f3f2f3",
      gray5: "#f7f7f8",
      gray6: "#e2e850",
      gray7: "#dddddd",
      lightOrange: "#F3ECD7",
      bgBody: "#f5f5f5",
      bgTFooter: "#ead9a8",
      lightBlack: "rgba(0, 0, 0, 0.4)",
      lightBlack2: "#121212",
      supportColor1: "#ffedea",
      supportColor2: "#f0eeff",
      overlayBg: "rgba(0, 0, 0, 0.6)",
      bgMaestro: "rgba(244, 237, 228, 1)",
      bgRange: "#ae923f",
      gradient1:
        "linear-gradient(180deg, rgba(248, 248, 248, 0) 0%, #F8F8F8 51.56%, rgba(248, 248, 248, 0) 100%)",
      gradient2:
        "linear-gradient(352.74deg, #4B2B5D 11.19%, rgba(75, 43, 93, 0.86) 41.4%, rgba(75, 43, 93, 0) 72.48%);",
      gradient3: "linear-gradient(180deg, #F4EDE4 0%, #F4EDE4 107.8%);",
    },
  },

  textStyles: {
    h1: {
      fontSize: ["28px", "28px", "28px", "28px", "19rem", "19rem"],
      fontWeight: ["bold"],
      lineHeight: "1.53",
      letterSpacing: "0.3px",
    },
    h2: {
      fontSize: ["20px", "20px", "24px", "24px", "26px", "26px"],
      fontWeight: ["bold"],
      lineHeight: "1.53",
      letterSpacing: "0.3px",
    },
    h3: {
      fontSize: "md",
      fontWeight: "700",
      lineHeight: "1.53",
      letterSpacing: "0.3px",
    },
    bodyText1: {
      fontSize: { base: "sm", md: "md" },
      fontWeight: ["normal"],
      lineHeight: ["1.75"],
      color: "primary.black",
      letterSpacing: ["0.3px"],
      fontFamily: "Inter",
    },
    bodyText2: {
      fontSize: "sm",
      fontWeight: ["normal"],
      lineHeight: ["1.75"],
      color: "primary.black",
      letterSpacing: ["0.3px"],
      fontFamily: "Inter",
    },
    bodyText3: {
      fontSize: ["fs13"],
      fontWeight: ["normal"],
      lineHeight: ["1.75"],
      color: "primary.black",
      letterSpacing: ["0.3px"],
      fontFamily: "Inter",
      letterSpacings: "wider",
    },
    bodyText4: {
      fontSize: ["fs13"],
      fontWeight: ["normal"],
      lineHeight: ["1.75"],
      color: "primary.white",
      letterSpacing: ["0.3px"],
      fontFamily: "Inter",
      letterSpacings: "wider",
    },
    bodyTextSd: {
      fontSize: { base: "24px", md: "28px", lg: "fs125" },
      fontWeight: ["normal"],
      lineHeight: ["1.75"],
      color: "primary.white",
      letterSpacing: ["0.3px"],
      fontFamily: "nanum",
    },
    newsCardSection: {
      pb: "8",
      mb: "8",
      borderBottom: "none",
      color: "primary.black",
      _notLast: {
        borderBottom: "1px solid",
        borderColor: "borderColor.color1",
      },
    },
    navHeadingMobile: {
      bg: "background.gray1",
      w: "full",
      borderBottom: "1px solid",
      borderTop: "1px solid",
      borderColor: "borderColor.color1",
      px: "4",
      py: "2",
      mb: "1",
      color: "primary.color1",
      fontSize: "md",
      fontWeight: ["bold"],
      lineHeight: ["1.75"],
      letterSpacing: "0.3px",
      fontFamily: '"Playfair Display", sans-serif',
    },
    tdLft: {
      fontSize: "fs13",
      fontWeight: "normal",
      w: "70%",
      lineHeight: "1.5",
      color: "red",
    },
  },
  components: {
    Container: {
      variants: {
        outerContainer,
      },
    },
    Heading: {
      variants: {
        display1: {
          fontSize: ["32px", "32px", "40px", "19rem", "19rem", "19rem"],
          fontWeight: ["bold"],
          lineHeight: ["1.75"],
          color: "primary.black",
          letterSpacing: ["normal"],
          fontFamily: "playfair",
        },
        h1: {
          fontSize: ["28px", "28px", "28px", "28px", "19rem", "19rem"],
          fontWeight: "noraml",
          lineHeight: "90%",
          letterSpacing: "-.03em",
          textTransformation: "uppercase",
          color: "white",
          fontFamily: "rubik",
        },
        h2: {
          fontSize: ["20px", "20px", "24px", "24px", "26px", "26px"],
          fontWeight: ["bold"],
          lineHeight: "1.53",
          letterSpacing: "0.3px",
        },
        h3: {
          fontSize: ["16px", "16px", "16px", "16px", "16px", "16px"],
          fontWeight: ["bold"],
          lineHeight: "1.53",
          letterSpacing: "0.3px",
        },
        h4: {
          color: "primary.color3",
          fontSize: "14px!important",
          fontWeight: ["bold"],
          lineHeight: "1.1",
          letterSpacing: "0.03em",
        },
        h5: {
          color: "primary.color3",
          fontSize: "fs13!important",
          fontWeight: ["semibold"],
          lineHeight: "1.1",
          letterSpacing: "0.03em",
        },
        contactPersonHeading: {
          fontSize: ["14px", "14px", "16px"],
          fontWeight: ["bold"],
          lineHeight: "1.53",
          letterSpacing: "0.3px",
          fontFamily: "inter",
        },
        maestroHeading1: {
          color: "primary.black",
          fontSize: ["26px", null, "2xl"],
          fontWeight: ["semibold"],
          lineHeight: "base",
          letterSpacing: "0.03em",
        },
        maestroHeading2: {
          color: "primary.black",
          fontSize: ["fs13", null, "fs11"],
          fontWeight: ["semibold"],
          lineHeight: "1.34rem",
          letterSpacing: "0.03em",
        },
      },
    },
    Text: {
      variants: {
        display1: {
          fontSize: ["32px", "32px", "40px", "40px", "40px", "40px"],
          fontWeight: ["bold"],
          lineHeight: ["1.75"],
          color: "primary.color2",
          letterSpacing: ["normal"],
          fontFamily: "playfair",
        },
        h1: {
          fontSize: ["28px", "28px", "28px", "28px", "19rem", "19rem"],
          fontWeight: "noraml",
          lineHeight: "-.03em",
          textTransformation: "uppercase",
          color: "white",
          fontFamily: "rubik",
        },
        h2: {
          fontSize: ["20px", "20px", "24px", "24px", "26px", "26px"],
          fontWeight: ["bold"],
          lineHeight: "1.53",
          letterSpacing: "0.3px",
        },
        bodyText1: {
          fontSize: { base: "sm", md: "md" },
          fontWeight: ["normal"],
          lineHeight: ["1.75"],
          color: "primary.black",
          letterSpacing: ["normal"],
          fontFamily: "Inter",
        },
        bodyText2: {
          fontSize: ["sm"],
          fontWeight: ["normal"],
          lineHeight: ["1.75"],
          color: "primary.black",
          letterSpacing: ["normal"],
          fontFamily: "Inter",
        },
        bodyText3: {
          fontSize: ["fs13"],
          fontWeight: ["normal"],
          lineHeight: ["1.75"],
          color: "primary.black",
          letterSpacing: ["normal"],
          fontFamily: "Inter",
        },
        bodyText4: {
          fontSize: ["fs13"],
          fontWeight: ["normal"],
          lineHeight: ["1.75"],
          color: "primary.white",
          letterSpacing: ["normal"],
          fontFamily: "Inter",
        },
        bodyTextSd: {
          fontSize: { base: "24px", md: "28px", lg: "125px" },
          fontWeight: ["normal"],
          lineHeight: ["1.2"],
          color: "primary.white",
          letterSpacing: ["0.3px"],
          fontFamily: "nanum",
        },
        bodyTextSdTags: {
          fontSize: "14px",
          fontWeight: "100",
          lineHeight: ["0.2"],
          color: "primary.white",
          paddingX: "0.8rem",
          paddingY: "1.2rem",
          margin: "0.7rem",
          display: "inline-block",
          border: "1px solid",
          borderRadius: "49px",
          letterSpacing: ["0.3px"],
          fontFamily: "nanum",
          textTransform: "uppercase",
        },
        linkStyle1: {
          display: "block",
          fontSize: "fs13",
          color: "primary.black",
          mt: "10px",
          transition: "all .3s ease",
          _hover: {
            textDecoration: "none",
            fontWeight: "bold",
            color: "primary.color3",
          },
          _activeLink: {
            textDecoration: "none",
            fontWeight: "bold",
            color: "primary.black",
          },
        },
        courseModeWithIcon: {
          fontSize: "sm",
          fontWeight: ["normal"],
          lineHeight: ["1.75"],
          color: "primary.black",
          letterSpacing: ["0.3px"],
          fontFamily: "Inter",
          position: "relative",
          mb: "3",
          pl: "8",
          _before: {
            content: '""',
            position: "absolute",
            width: "24px",
            height: "24px",
            backgroundImage: "url('/tick-circle.svg')",
            left: 0,
            top: "0",
          },
        },
        dotListStyle: {
          position: "relative",
          fontSize: ["fs13"],
          fontWeight: ["normal"],
          lineHeight: ["1.75"],
          color: "primary.black",
          letterSpacing: ["0.3px"],
          fontFamily: "Inter",
          letterSpacings: "wider",
          mb: "1",
          ps: "5",
          _before: {
            content: '""',
            position: "absolute",
            top: "2.5",
            left: 0,
            w: "1",
            h: "1",
            mb: "0",
            ms: "6px",
            me: "2",
            bg: "primary.black",
            borderRadius: "full",
          },
        },
        contactInfo: {
          position: "relative",
          fontSize: { base: "sm", md: "md" },
          fontWeight: ["normal"],
          lineHeight: ["1.5"],
          color: "primary.black",
          letterSpacing: ["0.3px"],
          fontFamily: "Inter",
          letterSpacings: "wider",
          mb: { base: "1", md: "2" },
          ps: "4",
          _before: {
            content: '""',
            position: "absolute",
            top: { base: "2", md: "10px" },
            left: 0,
            w: "6px",
            h: "6px",
            mb: "0",
            bg: "primary.black",
            borderRadius: "full",
          },
        },
        eventContactInfo: {
          position: "relative",
          fontSize: ["fs13"],
          fontWeight: ["normal"],
          lineHeight: ["21px"],
          color: "primary.black",
          letterSpacing: ["0.3px"],
          fontFamily: "Inter",
          letterSpacings: "wider",
          mb: "2px",
          ps: "4",
          _before: {
            content: '""',
            position: "absolute",
            top: { base: "2", md: "10px" },
            left: 0,
            w: "4px",
            h: "4px",
            mb: "0",
            bg: "primary.black",
            borderRadius: "full",
          },
        },
        tdLft: {
          fontSize: "fs13",
          lineHeight: ["1.25"],
          letterSpacing: "widest",
          w: { base: "full", md: "70%" },
          fontWeight: "bold",
        },
        columnCountText: {
          fontSize: { base: "sm", md: "md" },
          fontWeight: ["normal"],
          lineHeight: ["1.75"],
          color: "primary.black",
          letterSpacing: ["normal"],
          fontFamily: "Inter",
          mb: "4",
        },
        subNavLink: {
          fontSize: "fs13",
          position: "relative",
          color: "secondary.lightText1",
          fontWeight: "normal",
          transition: "all .2s ease",
          py: "22px",
          display: "flex",

          _hover: {
            color: "white",
            fontWeight: "semibold",
            textDecoration: "none",
            _before: {
              content: '""',
              position: "absolute",
              bottom: 0,
              left: 0,
              w: "full",
              h: "1",
              mb: "0",
              bg: "background.bgSubNavActive",
              borderTopLeftRadius: "4px",
              borderTopRightRadius: "4px",
              zIndex: "20",
            },
          },
          _activeLink: {
            color: "white",
            fontWeight: "semibold",
            _before: {
              content: '""',
              position: "absolute",
              bottom: 0,
              left: 0,
              w: "full",
              h: "1",
              mb: "0",
              bg: "background.bgSubNavActive",
              borderTopLeftRadius: "4px",
              borderTopRightRadius: "4px",
              zIndex: "20",
            },
          },
        },
        linkStyle2: {
          cursor: "pointer",
          position: "relative",
          bg: "transparent",
          fontSize: "fs13",
          fontWeight: "normal",
          _hover: {
            color: "primary.black",
            bg: "transparent",
            fontWeight: "semibold",
            textDecoration: "none",
            _before: {
              content: '""',
              position: "absolute",
              bottom: 0,
              left: 0,
              w: "full",
              h: "1",
              mb: "-4px",
              bg: "primary.color3",
              borderTopLeftRadius: "4px",
              borderTopRightRadius: "4px",
            },
          },
          _active: {
            color: "primary.black",
            fontWeight: "semibold",
            _before: {
              content: '""',
              position: "absolute",
              bottom: 0,
              left: 0,
              w: "full",
              h: "1",
              mb: "-4px",
              bg: "primary.color3",
              borderTopLeftRadius: "4px",
              borderTopRightRadius: "4px",
            },
          },
          _activeLink: {
            color: "primary.black",
            fontWeight: "semibold",
            _before: {
              content: '""',
              position: "absolute",
              bottom: 0,
              left: 0,
              w: "full",
              h: "1",
              mb: "-4px",
              bg: "primary.color3",
              borderTopLeftRadius: "4px",
              borderTopRightRadius: "4px",
            },
          },
        },
        onlinecrsBannerTxt: {
          fontSize: ["4xl", "4xl", "4xl", "fs69", "fs69", "fs69"],
          lineHeight: ["60px", "60px", "60px", "92.53px", "92.53px", "92.53px"],
        },
        primaryStyle3: {
          cursor: "pointer",
          bg: "primary.color3",
          fontSize: "sm",
          borderRadius: "45px",
          color: "white",
          fontWeight: "bold",
          transition: "all .3s ease",
          px: "10",
          py: "2",
          _hover: {
            bg: "primary.color1",
            _disabled: {
              bg: "primary.color1",
            },
          },
          _active: {
            bg: "primary.color1",
            fontWeight: "bold",
          },
          _disabled: {
            bg: "primary.color1",
          },
        },
        navMainLinkMobile: {
          px: "4",
          py: "2",
          marginTop: "0!important",
          fontSize: "fs13",
          color: "primary.black",
          fontWeight: "normal",
          display: "inline-block",
          textAlign: "left",
          // borderBottom: '1px solid',
          // borderColor: 'borderColor.color1',
          w: "full",
          _activeLink: {
            color: "primary.color1",
            fontWeight: "semibold",
          },
          _hover: {
            textDecoration: "none",
            color: "primary.color1",
          },
        },
        linkStyle3: {
          display: "inline-block",
          fontSize: "md",
          fontWeight: "bold",
          color: "primary.color2",
          mt: "10px",
          transition: "all .2s ease",
          textDecoration: "none",
          _hover: {
            textDecoration: "none",
          },
        },
        accomplishText: {
          fontSize: ["fs13"],
          fontWeight: ["normal"],
          lineHeight: ["1.75"],
          color: "primary.color1",
          letterSpacing: ["normal"],
          fontFamily: "Inter",
          me: "1",
        },
        homepageBannerBigText: {
          fontSize: ["2xl", "2xl", "50px"],
          lineHeight: ["6", "6", "10"],
          letterSpacing: ["0.14", "0.14", "0.3px"],
          fontFamily: "berkshire",
          px: "6",
          color: "white",
        },
      },
    },
    Button: {
      variants: {
        primaryStyle: {
          cursor: "pointer",
          bg: "transparent",
          fontSize: "10rem",
          borderRadius: "1000px",
          color: "#e0fd60",
          fontWeight: "normal",
          fontFamily: "rubik",
          transition: "all .5s ease",
          height: { base: "9", lg: "13rem" },
          border: "1px solid",
          borderColor: "#e0fd60",
          px: "4",
          _hover: {
            backgroundColor: "#e0fd60",
            color: "#000000",
            borderColor: "#e0fd60",
            transform: "scale(1.08)",
            transition: "all .9s ease",
          },
          _active: {
            bg: "#e0fd60",
            color: "#000000",
            borderColor: "#e0fd60",
          },
          _disabled: {
            bg: "primary.color1",
          },
        },
        primaryStyle2: {
          cursor: "pointer",
          bg: "primary.color2",
          fontSize: "sm",
          borderRadius: "24px",
          color: "white",
          fontWeight: "bold",
          py: "2",
          px: "10",
          transition: "all .3s ease",
          height: { base: "9", lg: "10" },
          _hover: {
            bg: "primary.color2",
            _disabled: {
              bg: "primary.color1",
            },
          },
          _active: {
            bg: "primary.color2",
            fontWeight: "600",
          },
          _disabled: {
            bg: "primary.color1",
          },
        },
        headerButton: {
          cursor: "pointer",
          bg: "primary.color1",
          fontSize: "sm",
          borderRadius: "24px",
          color: "white",
          fontWeight: "bold",
          transition: "all .3s ease",
          height: { base: "8", lg: "10" },
          _hover: {
            bg: "primary.color2",
            _disabled: {
              bg: "primary.color1",
            },
          },
          _active: {
            bg: "primary.color2",
            fontWeight: "600",
          },
          _disabled: {
            bg: "primary.color1",
          },
        },
        outlineStyle: {
          cursor: "pointer",
          bg: "transparent",
          border: "2px solid",
          borderColor: "primary.color1",
          fontSize: "sm",
          borderRadius: "24px",
          color: "primary.color1",
          fontWeight: "bold",
          height: { base: "9", lg: "10" },
          px: { base: "4", lg: "7" },
          transition: "all .3s ease",
          _hover: {
            bg: "primary.color1",
            border: "2px solid",
            borderColor: "primary.color1",
            color: "white",
          },
          _active: {
            bg: "primary.color1",
            color: "white",
          },
        },
        primaryStyle3: {
          cursor: "pointer",
          bg: "primary.color3",
          fontSize: "sm",
          borderRadius: "45px",
          color: "white",
          fontWeight: "bold",
          transition: "all .3s ease",
          px: "10",
          py: "2",
          _hover: {
            bg: "primary.color1",
            _disabled: {
              bg: "primary.color1",
            },
          },
          _active: {
            bg: "primary.color1",
            fontWeight: "bold",
          },
          _disabled: {
            bg: "primary.color1",
          },
        },
        subNavLink: {
          fontSize: "fs13",
          position: "relative",
          color: "secondary.lightText1",
          fontWeight: "normal",
          transition: "all .2s ease",
          py: "22px",
          px: "2",
          h: "auto",
          display: "flex",

          _hover: {
            color: "white",
            fontWeight: "semibold",
            textDecoration: "none",
            _before: {
              content: '""',
              position: "absolute",
              bottom: 0,
              left: 0,
              w: "full",
              h: "1",
              mb: "0",
              bg: "background.bgSubNavActive",
              borderTopLeftRadius: "4px",
              borderTopRightRadius: "4px",
              zIndex: "20",
            },
          },
          _activeLink: {
            color: "white",
            fontWeight: "semibold",
            _before: {
              content: '""',
              position: "absolute",
              bottom: 0,
              left: 0,
              w: "full",
              h: "1",
              mb: "0",
              bg: "background.bgSubNavActive",
              borderTopLeftRadius: "4px",
              borderTopRightRadius: "4px",
              zIndex: "20",
            },
          },
        },
        googleBtn: {
          bg: "transparent",
          border: "1px solid",
          borderColor: "borderColor.color1",
          fontSize: "md",
          py: "22px",
          borderRadius: "4px",
          color: "primary.lightBlack",
          fontWeight: "normal",
          _hover: {
            bg: "primary.color1",
            border: "1px solid",
            borderColor: "primary.color1",
            color: "white",
          },
          _active: {
            bg: "primary.color3",
            color: "white",
          },
        },
        navMainLinkMobile: {
          px: "4",
          py: "2",
          marginTop: "0!important",
          fontSize: "fs13",
          color: "primary.black",
          fontWeight: "normal",
          display: "inline-block",
          textAlign: "left",
          // borderBottom: '1px solid',
          // borderColor: 'borderColor.color1',
          w: "full",
          _activeLink: {
            color: "primary.color1",
            fontWeight: "semibold",
          },
          _hover: {
            textDecoration: "none",
            color: "primary.color1",
          },
        },
        navLink: {
          cursor: "pointer",
          bg: "transparent",
          fontSize: "fs13",
          px: "0",
          mr: "6",
          fontWeight: "normal",
          color: "primary.black",
          transition: "all .3s ease",
          _hover: {
            color: "primary.black",
            bg: "transparent",
            fontWeight: "semibold",
            _before: {
              content: '""',
              position: "absolute",
              bottom: 0,
              left: 0,
              w: "full",
              h: "1",
              mb: "-23px",
              bg: "primary.color3",
              borderTopLeftRadius: "4px",
              borderTopRightRadius: "4px",
            },
          },
          _activeLink: {
            bg: "transparent",
            color: "primary.black",
            fontWeight: "semibold",
            _before: {
              content: '""',
              position: "absolute",
              bottom: 0,
              left: 0,
              w: "full",
              h: "1",
              mb: "-23px",
              bg: "primary.color3",
              borderTopLeftRadius: "4px",
              borderTopRightRadius: "4px",
            },
          },
          _active: {
            color: "primary.color3",
            fontWeight: "semibold",
            _before: {
              content: '""',
              position: "absolute",
              bottom: 0,
              left: 0,
              w: "full",
              h: "1",
              mb: "-23px",
              bg: "primary.color3",
              borderTopLeftRadius: "4px",
              borderTopRightRadius: "4px",
            },
          },
        },
        navLogin: {
          cursor: "pointer",
          bg: "transparent",
          fontSize: "fs13",
          px: "0",
          mr: "3",
          h: "auto",
          transition: "all .3s ease",
          fontWeight: "normal",
          color: "primary.black",
          _hover: {
            bg: "transparent",
            fontWeight: "semibold",
            _before: {
              content: '""',
              position: "absolute",
              bottom: 0,
              left: 0,
              w: "full",
              h: "1",
              mb: "-6px",
              bg: "primary.color3",
              borderTopLeftRadius: "4px",
              borderTopRightRadius: "4px",
            },
          },
          _activeLink: {
            bg: "transparent",
            color: "primary.color1",
            fontWeight: "semibold",
            _before: {
              content: '""',
              position: "absolute",
              bottom: 0,
              left: 0,
              w: "full%",
              h: "1",
              mb: "-6px",
              bg: "primary.color3",
              borderTopLeftRadius: "4px",
              borderTopRightRadius: "4px",
            },
          },
          _active: {
            color: "primary.color3",
            fontWeight: "semibold",
            _before: {
              content: '""',
              position: "absolute",
              bottom: 0,
              left: 0,
              w: "full",
              h: "1",
              mb: "-6px",
              bg: "primary.color3",
              borderTopLeftRadius: "4px",
              borderTopRightRadius: "4px",
            },
          },
        },
        jbPopoverBtn: {
          position: "relative",
          height: "unset",
          fontSize: "sm",
          fontWeight: "normal",
          whiteSpace: "wrap",
          textAlign: "left",
          px: "4",
          lineHeight: "21px",
          _before: {
            content: '""',
            position: "absolute",
            width: "8px",
            height: "8px",
            backgroundImage: "url('/leafIcon.svg')",
            left: 0,
            top: "6px",
          },

          _hover: {
            bg: "background.bgTransparent",
          },
          _disabled: {
            bg: "background.bgTransparent",
          },
        },

        linkBtn: {
          cursor: "pointer",
          bg: "transparent",
          display: "block",
          margin: "auto",
          fontSize: "sm",
          h: "7",
          px: "4",
          fontWeight: "bold",
          color: "primary.color3",
          _hover: {
            bg: "transparent",
            color: "primary.color2",
          },
          _active: {
            color: "primary.color2",
          },
        },
        linkBtn2: {
          cursor: "pointer",
          bg: "transparent",
          display: "block",
          margin: "auto",
          fontSize: "md",
          px: "4",
          pt: "2",
          fontWeight: "bold",
          color: "primary.color1",
          _hover: {
            bg: "transparent",
            color: "primary.color2",
          },
          _active: {
            color: "primary.color2",
          },
        },
        subscribe: {
          h: "1.75rem",
          p: "4",
          mr: [6],
          mt: [3],
          lineHeight: [0],
          backgroundColor: "primary.black",
          color: "primary.white",
          fontSize: ["xs", "xs", "xs"],
          _focus: { boxShadow: "none", backgroundColor: "primary.black" },
        },
        invisible: {
          backgroundColor: "transparent",
          p: [0],
          m: [0],
          _focus: { boxShadow: "none" },
          _hover: { backgroundColor: "transparent" },
          _active: { backgroundColor: "transparent" },
        },
        myCouseChevronUp: {
          px: "4",
          py: "2",
          bg: "secondary.lightBg",
          borderRadius: "136px",
          position: "absolute",
          bottom: "0",
          right: "0",
        },
      },
    },
    Form: {
      variants: {
        floating: {
          container: {
            _focusWithin: {
              label: {
                ...activeLabelStyles,
              },
            },
            "input:not(:placeholder-shown) + label, .chakra-select__wrapper + label":
              {
                ...activeLabelStyles,
              },
            "textarea:not(:placeholder-shown) + label, .chakra-select__wrapper + label":
              {
                ...activeLabelStyles,
              },
            label: {
              top: "8px",
              left: 0,
              zIndex: 2,
              position: "absolute",
              backgroundColor: "white",
              pointerEvents: "none",
              mx: 3,
              px: 1,
              color: "primary.lightBlack",
              transformOrigin: "left top",
              fontSize: "md",
              fontWeight: "normal",
              _invalid: { textColor: "error" },
            },
            input: {
              fontSize: "md",
              fontWeight: "normal",
              ps: 4,
              py: "8px",
              bg: "white",
              borderColor: "borderColor.color1",
              _autofill: {
                borderColor: "primary.color1",
                boxShadow: "0 0 0px 1000px #fff inset",
                transition: "background-color 5000s ease-in-out 0s",
              },
              _focusVisible: {
                borderColor: "primary.black",
                boxShadow: "none",
              },
              _invalid: {
                borderColor: "error",
                boxShadow: "none",
              },
              _placeholder: {
                color: "primary.lightBlack",
              },
            },
            textarea: {
              fontSize: "md",
              fontWeight: "normal",
              ps: 4,
              py: "8px",
              bg: "white",
              borderColor: "borderColor.color1",
              _autofill: {
                borderColor: "primary.color1",
                boxShadow: "0 0 0px 1000px #fff inset",
                transition: "background-color 5000s ease-in-out 0s",
              },
              _focusVisible: {
                borderColor: "primary.black",
                boxShadow: "none",
              },
              _invalid: {
                borderColor: "error",
                boxShadow: "none",
              },
              _placeholder: {
                color: "primary.lightBlack",
              },
            },
          },
        },
        fileUploading: {
          container: {
            _focusWithin: {
              label: {
                ...activeLabelStyles,
              },
            },
            label: {
              top: "8px",
              left: 0,
              zIndex: 2,
              position: "absolute",
              backgroundColor: "white",
              pointerEvents: "none",
              mx: 3,
              px: 1,
              color: "primary.lightBlack",
              transformOrigin: "left top",
              fontSize: "md",
              fontWeight: "normal",
              textAlign: "center",
              _invalid: { textColor: "error" },
            },
            input: {
              fontSize: "md",
              fontWeight: "normal",
              width: "full",
              height: "full",
              position: "relative",
              p: "58px",
              bg: "white",
              borderStyle: "dashed",
              borderColor: "borderColor.color1",
            },
          },
        },
      },
    },
    Tabs: {
      variants: {
        lineStyle: {
          tab: {
            px: "0",
            pt: "0",
            mt: "0",
            color: "primary.black",
            fontSize: "md",
            fontWeight: "normal",
            fontFamily: "inter",
            borderBottom: "1px solid",
            borderColor: "background.bgTransparent",
            position: "relative",

            _selected: {
              color: "primary.black",
              fontWeight: "bold",
              pb: "3",
              borderBottom: "4px solid",
              borderColor: "primary.color3",
              boxShadow: "none",
              zIndex: "1",
            },
            _hover: {
              color: "primary.black",
              borderBottom: "4px solid",
              borderColor: "primary.color3",
              fontWeight: "bold",
              zIndex: "1",
            },
            _active: {
              color: "primary.color1",
              fontWeight: "bold",
              borderBottom: "4px solid",
              borderColor: "primary.color3",
              boxShadow: "none",
              zIndex: "1",
            },
          },
        },
        linkTab: {
          tab: {
            px: "0",
            mt: "0",
            me: "34px",
            color: "primary.color5",
            fontSize: "md",
            fontWeight: "normal",
            fontFamily: "inter",
            position: "relative",

            _selected: {
              color: "primary.color1",
              fontWeight: "bold",
              boxShadow: "none",
            },
            _hover: {
              color: "primary.color1",
              fontWeight: "bold",
            },
            _active: {
              color: "primary.color1",
              fontWeight: "bold",
              boxShadow: "none",
            },
          },
        },
        journeyTab: {
          tab: {
            px: "0",
            mt: "0",
            me: "8",
            color: "white",
            bgImage: 'url("/JourneyTabBg.svg")',
            bgRepeat: "no-repeat",
            bgSize: "contain",
            w: "7.125rem",
            h: "5.313rem",
            fontSize: "md",
            fontWeight: "bold",
            fontFamily: "inter",
            position: "relative",
            _odd: {
              mt: "5.3125rem",
              mb: "4",
            },
            _even: {
              mt: "-5.3125rem",
              mb: "4",
            },
            _selected: {
              color: "white",
              boxShadow: "none",
              bgImage: 'url("/JourneyTabBgActive.svg")',
              bgRepeat: "no-repeat",
              w: "114px",
              h: "85px",
            },
            // _hover: {
            //   fontWeight: 'bold',
            // },
          },
        },
        tagTabbing: {
          tab: {
            p: "2",
            mt: "0",
            color: "primary.black",
            fontSize: "fs13",
            fontWeight: "normal",
            fontFamily: "inter",
            background: "background.gray5",
            borderRadius: "6px",
            position: "relative",

            _selected: {
              background: "secondary.lightText1",
              fontWeight: "semibold",
            },
            _hover: {
              background: "secondary.lightText1",
              fontWeight: "semibold",
            },
            _active: {
              background: "secondary.lightText1",
              fontWeight: "semibold",
            },
          },
        },
      },
    },
    Accordion: {
      variants: {
        themeStyle: {
          container: {
            border: "0",
            mb: "2",
          },
          button: {
            position: "relative",
            bg: "background.gray5",
            _hover: {
              bg: "background.gray5",
            },
            _active: {
              bg: "background.gray5",
            },
          },
          panel: {
            background: "white",
            border: "none",
            fontSize: "fs13",
            pb: ["4", "null", "null", "6"],
            mt: "2",
            color: "primary.black",
          },
          icon: {},
        },
        dashboardAccordition: {
          container: {
            border: "0",
            mb: "2",
          },
          button: {
            border: "1px solid",
            borderColor: "background.gray7",
            borderRadius: "lg",
            display: "block",
            textAlign: "left",
            p: "6",
            bg: "white",
            _hover: {
              bg: "white",
              borderColor: "background.bgRange",
            },
            _focus: {
              borderColor: "background.bgRange",
            },
          },
          panel: {
            position: "relative",
            p: "0",
            mt: "2",
            cursor: "pointer",
            border: "none",
            borderRadius: "lg",
            color: "primary.black",
          },
          icon: {},
        },
        recordedAccordition: {
          container: {
            border: "0",
            mb: "2",
            bg: "background.gray4",
            borderRadius: "lg",
            overflow: "hidden",
            fontFamily: "inter",
          },
          button: {
            display: "block",
            padding: "0 !important",
            margin: "0 !important",
          },
          panel: {
            padding: "0 ",
            px: ["2", null, "4"],
            mb: "4",
          },
          icon: {},
        },
      },
    },
    Link: {
      variants: {
        primaryStyleLink: {
          cursor: "pointer",
          bg: "primary.color1",
          fontSize: "sm",
          borderRadius: "24px",
          color: "white",
          fontWeight: "normal",
          px: { base: "4", lg: "8" },
          transition: "all .3s ease",
          lineHeight: { base: "9", lg: "10" },
          height: { base: "9", lg: "10" },
          _hover: {
            bg: "primary.color2",
            textDecoration: "none",
            _disabled: {
              bg: "primary.color1",
            },
          },
          _active: {
            bg: "primary.color2",
            fontWeight: "600",
          },
          _disabled: {
            bg: "primary.color1",
          },
        },
        linkStyle1: {
          display: "block",
          fontSize: "fs13",
          color: "primary.black",
          mt: "10px",
          transition: "all .3s ease",
          _hover: {
            textDecoration: "none",
            fontWeight: "bold",
            color: "primary.color3",
          },
          _activeLink: {
            textDecoration: "none",
            fontWeight: "bold",
            color: "primary.color3",
          },
        },
        linkStyle2: {
          cursor: "pointer",
          position: "relative",
          bg: "transparent",
          fontSize: "fs13",
          fontWeight: "normal",
          _hover: {
            bg: "transparent",
            fontWeight: "semibold",
            textDecoration: "none",
            _before: {
              content: '""',
              position: "absolute",
              bottom: 0,
              left: 0,
              w: "full",
              h: "1",
              mb: "-4px",
              bg: "primary.color3",
              borderTopLeftRadius: "4px",
              borderTopRightRadius: "4px",
            },
          },
          _active: {
            color: "primary.color3",
            fontWeight: "semibold",
            _before: {
              content: '""',
              position: "absolute",
              bottom: 0,
              left: 0,
              w: "full",
              h: "1",
              mb: "-4px",
              bg: "primary.color3",
              borderTopLeftRadius: "4px",
              borderTopRightRadius: "4px",
            },
          },
          _activeLink: {
            color: "primary.color3",
            fontWeight: "semibold",
            _before: {
              content: '""',
              position: "absolute",
              bottom: 0,
              left: 0,
              w: "full",
              h: "1",
              mb: "-4px",
              bg: "primary.color3",
              borderTopLeftRadius: "4px",
              borderTopRightRadius: "4px",
            },
          },
        },
        linkStyle3: {
          display: "inline-block",
          fontSize: "md",
          fontWeight: "bold",
          color: "primary.color2",
          mt: "10px",
          transition: "all .2s ease",
          textDecoration: "none",
          _hover: {
            textDecoration: "none",
          },
        },
        linkStyle4: {
          display: "inline-block",
          fontSize: "fs13",
          color: "white",
          transition: "all .2s ease",
          textDecoration: "none",
          _hover: {
            textDecoration: "none",
            color: "white",
          },
        },
        linkStyle5: {
          display: "inline-block",
          fontSize: "md",
          fontWeight: "bold",
          color: "primary.color3",
          mt: "10px",
          transition: "all .2s ease",
          textDecoration: "none",
          _hover: {
            textDecoration: "none",
          },
        },
        workLink: {
          display: "flex",
          fontSize: "fs13",
          fontWeight: "bold",
          color: "primary.color1",
          lineHeight: "5",
          mt: "10px",
          transition: "all .2s ease",
          textDecoration: "none",
          _hover: {
            textDecoration: "none",
            color: "primary.color2",
            svg: {
              circle: {
                fill: "primary.color2",
              },
              path: {
                fill: "primary.color2",
                stroke: "primary.color2",
              },
            },
          },
        },
        navMainLinkMobile: {
          px: "4",
          py: "2",
          marginTop: "0!important",
          fontSize: "fs13",
          color: "primary.black",
          fontWeight: "normal",
          // borderBottom: '1px solid',
          // borderColor: 'borderColor.color1',
          w: "full",
          _activeLink: {
            color: "primary.color1",
            fontWeight: "semibold",
          },
          _hover: {
            textDecoration: "none",
            color: "primary.color1",
          },
        },
        navTopLinkMobile: {
          display: "inline-block",
          fontSize: "md",
          fontWeight: "normal",
          color: "primary.black",
          mt: "0",
          transition: "all .2s ease",
          textDecoration: "none",
          _hover: {
            textDecoration: "none",
          },
          _active: {
            color: "primary.color1",
          },
        },
        subNavLink: {
          fontSize: "fs13",
          position: "relative",
          color: "secondary.lightText1",
          fontWeight: "normal",
          transition: "all .2s ease",
          py: "22px",
          display: "flex",

          _hover: {
            color: "white",
            fontWeight: "semibold",
            textDecoration: "none",
            _before: {
              content: '""',
              position: "absolute",
              bottom: 0,
              left: 0,
              w: "full",
              h: "1",
              mb: "0",
              bg: "background.bgSubNavActive",
              borderTopLeftRadius: "4px",
              borderTopRightRadius: "4px",
              zIndex: "20",
            },
          },
          _activeLink: {
            color: "white",
            fontWeight: "semibold",
            _before: {
              content: '""',
              position: "absolute",
              bottom: 0,
              left: 0,
              w: "full",
              h: "1",
              mb: "0",
              bg: "background.bgSubNavActive",
              borderTopLeftRadius: "4px",
              borderTopRightRadius: "4px",
              zIndex: "20",
            },
          },
        },
      },
    },
    Table: {
      variants: {
        bgStriped: {
          th: {
            w: "50%",
            px: "6",
            py: "2",
            lineHeight: "base",
            bg: "tableHeaderBg",
            fontSize: "fs13",
            textTransform: "capitalize",
            fontWeight: "normal",
            color: "primary.black",
            textAlign: "left",
            fontFamily: "inter",
            border: "1px solid",

            borderColor: "borderColor.color1",
            _first: {
              borderRight: "1px solid",
              borderColor: "borderColor.color1",
            },
          },
          td: {
            w: "50%",
            px: "6",
            py: "2",
            lineHeight: "base",
            // bg: 'background.gray5',
            fontSize: "fs13",
            color: "primary.black",
            fontWeight: "normal",
            textAlign: "left",
            fontFamily: "inter",
            verticalAlign: "top",
            border: "1px solid",

            borderColor: "borderColor.color1",
            _first: {
              borderRight: "1px solid",
              borderColor: "borderColor.color1",
            },
          },
        },
        radioTable: {
          th: {
            w: "full",
            px: "6",
            py: "2",
            lineHeight: "base",
            bg: "tableHeaderBg",
            fontSize: "fs13",
            textTransform: "capitalize",
            fontWeight: "normal",
            color: "primary.black",
            textAlign: "left",
            fontFamily: "inter",
            border: "1px solid",

            borderColor: "borderColor.color1",
            _first: {
              borderRight: "1px solid",
              borderColor: "borderColor.color1",
            },
          },
          td: {
            w: "full",
            px: "6",
            py: "2",
            lineHeight: "base",
            // bg: 'background.gray5',
            fontSize: "fs13",
            color: "primary.black",
            fontWeight: "normal",
            textAlign: "left",
            fontFamily: "inter",
            verticalAlign: "top",
            border: "1px solid",

            borderColor: "borderColor.color1",
            _first: {
              borderRight: "1px solid",
              borderColor: "borderColor.color1",
            },
          },
        },
        FeeStructure: {
          tr: {
            width: "full",
            _last: {
              bg: "secondary.lightBg",
            },
          },
          td: {
            w: "50%",
            px: "6",
            py: "2",
            lineHeight: "base",
            // bg: 'background.gray5',
            fontSize: "fs13",
            color: "primary.black",
            fontWeight: "normal",
            textAlign: "left",
            fontFamily: "inter",
            verticalAlign: "top",
            border: "1px solid",

            borderColor: "borderColor.color1",
            _first: {
              borderRight: "1px solid",
              borderColor: "borderColor.color1",
            },
          },
        },
      },
    },
    Radio: {
      variants: {
        primaryRadioButton: {
          control: {
            width: "5",
            height: "5",
            padding: "0",
            borderWidth: "1px",
            borderStyle: "solid",
            borderColor: "black",
            _checked: {
              bg: "white",
              borderWidth: "1px",
              borderStyle: "solid",
              borderColor: "black",
              color: "primary.color1",
              textAlign: "center",
              _before: {
                width: "3",
                height: "3",
              },
              _hover: {
                bg: "white",
                borderWidth: "1px",
                borderStyle: "solid",
                borderColor: "black",
                color: "primary.color1",
              },
            },
          },
          label: {
            fontSize: "md",
            fontWeight: "bold",
            lineHeight: "1.25",
          },
        },
      },
    },
    Select: {
      variants: {
        selectMonths: {
          field: {
            border: "0",
            bg: "background.gray4",
            fontSize: "fs13",
            lineHeight: "21px",
          },
        },
        selectCountryCode: {
          field: {
            border: "0",
            bg: "white",
            fontSize: "md",
            lineHeight: "21px",
            borderWidth: "1px",
            borderStyle: "solid",
            borderColor: "borderColor.color1",
            color: "primary.lightBlack",
            _hover: {
              borderColor: "black",
            },
          },
        },
      },
    },
    Checkbox: {
      variants: {
        primaryCheckBox: {
          control: {
            width: "5",
            height: "5",
            padding: "0",
            borderWidth: "1px",
            borderStyle: "solid",
            borderColor: "black",
            borderRadius: "full",
            bg: "white !important",
            _before: {
              width: "2",
              height: "2",
            },
            _hover: {
              bg: "white",
              borderWidth: "1px",
              borderStyle: "solid",
              color: "primary.color1",
              borderColor: "black",
            },
            _checked: {
              borderColor: "black",
            },
          },
          icon: {
            color: "primary.color1",
            bg: "primary.color1",
            border: "0",
            borderRadius: "full",
            w: "10px !important",
            h: "10px",
            // bg: 'white',
            // borderWidth: '1px',
            // borderStyle: 'solid',
            // borderColor: 'black',
            // color: 'primary.color1',
            // textAlign:'center',
            //  _before:{
            //   width:'2',
            //   height:'2',

            //  },
            // _hover: {
            //   bg: 'white',
            //   borderWidth: '1px',
            //   borderStyle: 'solid',
            //   borderColor: 'black',
            //   color: 'primary.color1',
            // }
          },
          label: {
            fontSize: "md",
            fontWeight: "bold",
            lineHeight: "1.25",
          },
        },
      },
    },
    List: {
      variants: {
        sessionList: {
          container: {
            mt: "4",
            p: "4",
          },
          item: {
            listStyle: "none",
            textAlign: "left",
          },
        },
      },
    },
  },
});
